<?php

$title = 'Add new BDR Client';
$this->headTitle($title);
?>
    <h1><?= $this->escapeHtml($title) ?></h1>
<?php

$name = $form->get('name');
$name->setAttribute('class', 'form-control');
$name->setAttribute('placeholder', 'Client');

$email = $form->get('email');
$email->setAttribute('class', 'form-control');
$email->setAttribute('placeholder', 'E-mail');

$phone = $form->get('phone');
$phone->setAttribute('class', 'form-control');
$phone->setAttribute('placeholder', 'Phone');

$picture = $form->get('picture');
$picture->setAttribute('class', 'form-control');
$picture->setAttribute('placeholder', 'Picture');

$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action', $this->url('bdr', ['action' => 'add']));
$form->prepare();

echo $this->form()->openTag($form);
?>
<?php // Wrap the elements in divs marked as form groups, and render the
// label, element, and errors separately within ?>
    <div class="form-group">
        <?= $this->formLabel($name) ?>
        <?= $this->formElement($name) ?>
        <?= $this->formElementErrors()->render($name, ['class' => 'help-block']) ?>
    </div>

    <div class="form-group">
        <?= $this->formLabel($email) ?>
        <?= $this->formElement($email) ?>
        <?= $this->formElementErrors()->render($email, ['class' => 'help-block']) ?>
    </div>

    <div class="form-group">
        <?= $this->formLabel($phone) ?>
        <?= $this->formElement($phone) ?>
        <?= $this->formElementErrors()->render($phone, ['class' => 'help-block']) ?>
    </div>

    <div class="form-element">
        <?php $fileElement = $form->get('picture'); ?>
        <?php echo $this->formLabel($fileElement); ?>
        <?php echo $this->formFile($fileElement); ?>
        <?php echo $this->formElementErrors($fileElement); ?>
    </div>

<?php
echo $this->formSubmit($submit);
echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag();
