<?php

$title = 'My BDR Clients';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<p>
    <a href="<?= $this->url('bdr', ['action' => 'add']) ?>">Add new Client</a>
</p>

<table class="table">
    <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Phone</th>
        <th>Picture</th>
        <th>&nbsp;</th>
    </tr>
    <?php foreach ($clients as $client) : ?>
        <tr>
            <td><?= $this->escapeHtml($client->name) ?></td>
            <td><?= $this->escapeHtml($client->email) ?></td>
            <td><?= $this->escapeHtml($client->phone) ?></td>
            <td><?= $this->escapeHtml($client->picture) ?></td>
            <td>
                <a href="<?= $this->url('bdr', ['action' => 'edit', 'id' => $client->id]) ?>">Edit</a>
                <a href="<?= $this->url('bdr', ['action' => 'delete', 'id' => $client->id]) ?>">Delete</a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>
